"""Gemini API client for content analysis"""
import json
import os
import requests
from datetime import datetime
from typing import Dict, Any, Optional, List


class GeminiClient:
    """Wrapper for Gemini API operations"""
    
    def __init__(self, api_key: Optional[str] = None):
        """Initialize Gemini client"""
        self.api_key = api_key or os.environ.get('GEMINI_API_KEY')
        self.base_url = "https://generativelanguage.googleapis.com/v1beta/models"

    def synthesize_content(self, query: str, contents: List[Dict[str, str]]) -> Dict[str, Any]:
        """Uses Gemini to synthesize an article from multiple sources."""
        if not self.api_key:
            return {'success': False, 'error': 'GEMINI_API_KEY not set'}

        # Prepare the source material for the prompt
        source_material = ""
        for i, doc in enumerate(contents):
            source_material += f"--- Source {i+1} ---\n"
            source_material += f"URL: {doc.get('url', 'N/A')}\n"
            source_material += f"Title: {doc.get('title', 'N/A')}\n"
            source_material += f"Content:\n{doc.get('markdown', '')[:2000]}\n\n" # Truncate

        # --- Load prompt from external file ---
        try:
            prompt_path = Path(__file__).parent.parent / 'intelligence' / 'config' / 'prompts' / 'synthesize_article_prompt.txt'
            with open(prompt_path, 'r', encoding='utf-8') as f:
                prompt_template = f.read()

            prompt = prompt_template.format(query=query, source_material=source_material)
        except Exception as e:
            return {'success': False, 'error': f'Failed to load prompt template: {str(e)}'}
        # -----------------------------------------

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"
        headers = {'Content-Type': 'application/json', 'X-goog-api-key': self.api_key}
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.7, "maxOutputTokens": 4096}
        }

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            result = response.json()

            raw_text = result['candidates'][0]['content']['parts'][0]['text']
            # A more robust way to find the JSON object
            json_start = raw_text.find('{')
            json_end = raw_text.rfind('}') + 1
            if json_start == -1 or json_end == 0:
                raise ValueError("No JSON object found in the AI response.")

            json_text = raw_text[json_start:json_end]
            parsed_result = json.loads(json_text)

            if parsed_result.get("article"):
                return {
                    'success': True,
                    'article': parsed_result.get("article"),
                    'outstaffer_analysis': parsed_result.get("outstaffer_analysis"),
                    'linkedin_post': parsed_result.get("linkedin_post")
                }
            else:
                return dict(success=False, error='No article was generated by the AI.')
        except (requests.exceptions.RequestException, ValueError, KeyError, json.JSONDecodeError) as e:
            return {
                'success': False,
                'error': f'Gemini API or parsing error: {str(e)}',
            }


    def analyze_content(self, content: str, prompt: str = None, model: str = "gemini-2.0-flash") -> Dict[str, Any]:
        """Analyze content with Gemini"""
        if not self.api_key:
            return {
                'success': False,
                'error': 'GEMINI_API_KEY not set',
                'analyzed_at': datetime.now().strftime("%Y%m%d_%H%M%S")
            }
        
        # Default analysis prompt tailored for Outstaffer
        if prompt is None:
            prompt = f"""
            Analyze this scraped web content and provide:

            1. **Executive Summary** (2-3 sentences): What's the core message?
            
            2. **Key Insights** (3-5 bullet points): Main takeaways relevant to recruitment/EOR industry
            
            3. **Outstaffer Relevance** (paragraph): How does this content relate to Outstaffer's business model (recruitment-led global hiring + EOR platform serving US staffing firms and Australian B2B companies)?
            
            4. **Content Angle Ideas** (3 suggestions): How could this be adapted into blog posts or thought leadership for Outstaffer?
            
            5. **Action Items** (2-3 points): Specific ways Outstaffer could leverage these insights
            
            Keep analysis concise, practical, and focused on business applications. Avoid fluff.
            
            CONTENT TO ANALYZE:
            {content}
            """
        
        url = f"{self.base_url}/{model}:generateContent"
        
        headers = {
            'Content-Type': 'application/json',
            'X-goog-api-key': self.api_key
        }
        
        payload = {
            "contents": [
                {
                    "parts": [
                        {
                            "text": prompt
                        }
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.7,
                "topK": 40,
                "topP": 0.95,
                "maxOutputTokens": 2048
            }
        }
        
        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            
            result = response.json()
            
            # Extract generated text
            generated_text = None
            if 'candidates' in result and len(result['candidates']) > 0:
                candidate = result['candidates'][0]
                if 'content' in candidate and 'parts' in candidate['content']:
                    generated_text = candidate['content']['parts'][0]['text']
                elif 'parts' in candidate:
                    generated_text = candidate['parts'][0]['text']
            
            if generated_text:
                return {
                    'success': True,
                    'analysis': generated_text,
                    'raw_response': result,
                    'analyzed_at': datetime.now().strftime("%Y%m%d_%H%M%S"),
                    'model': model
                }
            else:
                return {
                    'success': False,
                    'error': 'No content generated by Gemini',
                    'raw_response': result,
                    'analyzed_at': datetime.now().strftime("%Y%m%d_%H%M%S")
                }
                
        except requests.exceptions.RequestException as e:
            return {
                'success': False,
                'error': f'Gemini API error: {str(e)}',
                'analyzed_at': datetime.now().strftime("%Y%m%d_%H%M%S")
            }
